### ISSUE TITLE
tart_vis2json fails in create_direct_vis_dict

### ISSUE THREAD

**Issue by bennahugo** [tmolteno/tart_modules#1]
Trying to get json files out of h5 to test concatenation in tart2ms, but failing dismally to make them
```
tart_vis2json --vis ../NZ_2022_10_19/*.hdf                                                                                                                                            
Traceback (most recent call last):
  File "/home/hugo/workspace/venv3/bin/tart_vis2json", line 38, in <module>
    vis_dict = create_direct_vis_dict(vis)
  File "/home/hugo/workspace/venv3/bin/tart_vis2json", line 15, in create_direct_vis_dict
    for (b, v) in zip(vis.baselines, vis.v):
AttributeError: 'str' object has no attribute 'baselines'
```

**Comment by bennahugo** [comment]
Ok finally think I have something working (it is at least importing again in a full chain h5->json->ms

**Comment by tmolteno** [comment]
Great. I will do a new release soon.
